engines:
    phpmd:
        enabled: true
        checks:
            Controversial/CamelCasePropertyName:
                enabled: false
            CleanCode/StaticAccess:
                enabled: false
            Design/TooManyPublicMethods:
                enabled: false